version: "3.8"

services:
  # admin API database
  admin_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: book_admin
    ports:
      - "5435:5432"
    volumes:
      - postgres_admin_data:/var/lib/postgresql/data

  # Frontend API database
  frontend_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: book_frontend
    ports:
      - "5434:5432"
    volumes:
      - postgres_frontend_data:/var/lib/postgresql/data

  # Frontend API web service
  frontend_web:
    build:
      context: .
      dockerfile: frontend-api/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - frontend-api/.env
    depends_on:
      - frontend_db
  # Admin API web service
  admin_web:
    build:
      context: .
      dockerfile: admin-api/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - admin-api/.env
    depends_on:
      - admin_db

volumes:
  postgres_admin_data:
  postgres_frontend_data:
