version: "3.8"

services:
  # admin API database
  admin_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: book_admin
    ports:
      - "5435:5432"
    volumes:
      - postgres_admin_data:/var/lib/postgresql/data

  # Frontend API database
  frontend_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: book_frontend
    ports:
      - "5434:5432"
    volumes:
      - postgres_frontend_data:/var/lib/postgresql/data

  # Frontend API web service
  frontend_web:
    build:
      context: .
      dockerfile: frontend-api/Dockerfile
    ports:
      - "8001:8001"
    environment:
      JWT_SECRET_KEY: your_jwt_secret_key
      SQLALCHEMY_DATABASE_URL: postgresql://root:rootpassword@frontend_db:5432/book_frontend
      TEST_SQLALCHEMY_DATABASE_URL: postgresql://root:rootpassword@frontend_db:5432/book_frontend_test
      ALGORITHM: HS256
    depends_on:
      - frontend_db

  # Admin API web service
  admin_web:
    build:
      context: .
      dockerfile: admin-api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      JWT_SECRET_KEY: lohuhns
      SQLALCHEMY_DATABASE_URL: postgresql://root:rootpassword@admin_db:5432/book_admin
      TEST_SQLALCHEMY_DATABASE_URL: postgresql://root:rootpassword@admin_db:5432/book_admin_test
      ALGORITHM: HS256
    depends_on:
      - admin_db

volumes:
  postgres_admin_data:
  postgres_frontend_data:
